alias ZZ="cd .."
alias la="exa -alh -s type"
alias ls="exa -s type"
alias tree="exa -T"
alias uni="cd /home/samuel/Documentos/U"
alias p="sudo"
alias please="sudo"
alias cmatrix="cmatrix -C yellow"
alias e="exit"
alias android="jmtpfs"
alias uandroid="fusermount -u"
alias cl="clear"
alias v="nvim"
# alias lua="lua -i -e \"st = require'stats';mat = require'matrix'\""

